# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1ba78869f45414f085d5e2e4bc2c74634b0d47d4a9e6ee250a2a14db11b92d888e9e0818c9ae24617b744bc4b60b2302ff995ae85987818baf13c3c2781e66a

test:
  secret_key_base: 029db66ce54feea0fd304cd893e7b08dee90d7317dd14588d9678d1a75dbfada6418ef53582c5a22f8a7b4fd6cd42909b55ac3061e54d8aab371451414eadd9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
